version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql_mm'
    environment:
      MYSQL_DATABASE: 'practica'
      MYSQL_USER: 'me'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "3306:3306"
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - springboot-network

volumes:
  mysql_data:

networks:
  springboot-network:
    driver: bridge
