services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql_mm'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3307" 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 'backend_mm'
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080" 
    volumes:
      - backend_logs:/app/logs 
    networks:
      - springboot-network

volumes:
  mysql_data:
  backend_logs:

networks:
  springboot-network:
